export type BattleTeam = 'alpha' | 'omega'

export type BattleGift = {
  id: string
  name: string
  weapon: string
  baseCost: number
  power: number
  godmode: number
  effectClass: string
  animated: boolean
  animationName?: string
  videoSrc?: string   /* path relative to /public — e.g. '/gifts/01_Golden_Crown.webm' */
  description: string
}

export const BATTLE_DISCOUNT = 0.2
export const BATTLE_BREAKPOINT = 25
export const GODMODE_TARGET = 10
export const CREATOR_REVENUE_RATE = 0.85
export const NETWORK_DESIGNER_REVENUE_RATE = 0.15

export type BattleRevenueSplit = {
  gross: number
  creator: number
  networkDesigners: number
}

const ANIMATED_GIFTS = [
  {
    id: 'snowball',
    name: 'Direct Snowball',
    weapon: 'SNOWBALL',
    baseCost: 5,
    power: 1,
    godmode: 1,
    effectClass: 'snowball',
    animated: true,
    animationName: 'Direct snowburst hit',
    description: '+1 score and +1 Godmode on a direct hit.',
  },
] satisfies BattleGift[]

/* ── LEGENDARY gift — Golden Rose (exclusive, highest tier) ─────────────── */
const LEGENDARY_GIFTS: BattleGift[] = [
  {
    id: 'golden-rose',
    name: 'Golden Rose',
    weapon: '🌹',
    baseCost: 200,
    power: 12,
    godmode: 8,
    effectClass: 'solar',
    animated: true,
    animationName: 'Golden Rose',
    videoSrc: '/gifts/Golden_Rose.webm',
    description: '🌹 LEGENDARY — the rarest gift. Sends a golden rose to the target host. Maximum score + Godmode.',
  },
]

/**
 * NEW — Tick Tock Prime × Orion Key gift avatar concepts (2026-08-06).
 * Source: TickTockPrime-20-Gift-Avatar-Concepts/concepts-20-index.json
 * CSS battle FX until WebM avatars ship under /gifts/.
 */
const ORION_KEY_AVATAR_GIFTS: BattleGift[] = [
  {
    id: 'nebula-ghost',
    name: 'Nebula Ghost',
    weapon: '👻',
    baseCost: 36,
    power: 4,
    godmode: 2,
    effectClass: 'vortex',
    animated: true,
    animationName: 'Nebula Ghost',
    description: 'NEW · Rare — soft-glow spirit decrypts into a constellation face. Seal pulse locks the stars.',
  },
  {
    id: 'void-sentinel',
    name: 'Void Sentinel',
    weapon: '🛡️',
    baseCost: 68,
    power: 7,
    godmode: 3,
    effectClass: 'shield-break',
    animated: true,
    animationName: 'Void Sentinel',
    description: 'NEW · Epic — armor-plated guardian; cipher rings lock and stamp a gold key brand.',
  },
  {
    id: 'cipher-astronaut',
    name: 'Cipher Astronaut',
    weapon: '🧑‍🚀',
    baseCost: 16,
    power: 2,
    godmode: 1,
    effectClass: 'neon',
    animated: true,
    animationName: 'Cipher Astronaut',
    description: 'NEW · Common — explorer pins the sky; Secret → Sky pin → Seal HUD chevrons fill teal.',
  },
  {
    id: 'quantum-fox',
    name: 'Quantum Fox',
    weapon: '🦊',
    baseCost: 34,
    power: 4,
    godmode: 2,
    effectClass: 'spark-net',
    animated: true,
    animationName: 'Quantum Fox',
    description: 'NEW · Rare — trickster mascot weaves an Argon pressure helix and tosses a sealed capsule.',
  },
  {
    id: 'black-hole-crown',
    name: 'Black-Hole Crown',
    weapon: '👑',
    baseCost: 120,
    power: 10,
    godmode: 6,
    effectClass: 'solar',
    animated: true,
    animationName: 'Black-Hole Crown',
    description: 'NEW · Legendary — royalty at the event horizon; glyphs resolve into the Orion key.',
  },
  {
    id: 'geo-30-lattice-mage',
    name: 'Geo-30 Lattice Mage',
    weapon: '🧙',
    baseCost: 72,
    power: 7,
    godmode: 4,
    effectClass: 'godmode-key',
    animated: true,
    animationName: 'Geo-30 Lattice Mage',
    description: 'NEW · Epic — 30 sky nodes snap into a lattice mask; gold seal rune stamps the grid.',
  },
  {
    id: 'dual-control-twin-keys',
    name: 'Dual-Control Twin Keys',
    weapon: '🔑',
    baseCost: 130,
    power: 10,
    godmode: 6,
    effectClass: 'pulse-cannon',
    animated: true,
    animationName: 'Dual-Control Twin Keys',
    description: 'NEW · Legendary — A+B twin seals; dual rings nest into one sealed token halo.',
  },
  {
    id: 'argon-pressure-titan',
    name: 'Argon Pressure Titan',
    weapon: '💪',
    baseCost: 70,
    power: 7,
    godmode: 3,
    effectClass: 'thunder',
    animated: true,
    animationName: 'Argon Pressure Titan',
    description: 'NEW · Epic — memory-hard muscle; Argon pressure rings compress into a dense sealed core.',
  },
  {
    id: 'star-tracker-owl',
    name: 'Star-Tracker Owl',
    weapon: '🦉',
    baseCost: 14,
    power: 2,
    godmode: 1,
    effectClass: 'neon',
    animated: true,
    animationName: 'Star-Tracker Owl',
    description: 'NEW · Common — night watcher locks a sky-pin reticle; feathers flip to cipher side.',
  },
  {
    id: 'sealed-token-djinn',
    name: 'Sealed Token Djinn',
    weapon: '🧞',
    baseCost: 38,
    power: 5,
    godmode: 2,
    effectClass: 'vortex',
    animated: true,
    animationName: 'Sealed Token Djinn',
    description: 'NEW · Rare — wish granted only after seal; ciphertext smoke collapses into a token jewel.',
  },
  {
    id: 'mars-horizon-pilgrim',
    name: 'Mars Horizon Pilgrim',
    weapon: '🪐',
    baseCost: 66,
    power: 6,
    godmode: 3,
    effectClass: 'meteor',
    animated: true,
    animationName: 'Mars Horizon Pilgrim',
    description: 'NEW · Epic — multi-planetary trust; star compass locks and orbital seal descends.',
  },
  {
    id: 'cipher-seraph',
    name: 'Cipher Seraph',
    weapon: '🪽',
    baseCost: 118,
    power: 9,
    godmode: 5,
    effectClass: 'solar',
    animated: true,
    animationName: 'Cipher Seraph',
    description: 'NEW · Legendary — angel of sealed light; nested wing tags stamp a gold integrity halo.',
  },
  {
    id: 'pulse-code-comet-rider',
    name: 'Pulse-Code Comet Rider',
    weapon: '☄️',
    baseCost: 32,
    power: 4,
    godmode: 2,
    effectClass: 'meteor',
    animated: true,
    animationName: 'Pulse-Code Comet Rider',
    description: 'NEW · Rare — ride the signal; pulse-code trail resolves into a sealed key.',
  },
  {
    id: 'archive-horizon-leviathan',
    name: 'Archive-Horizon Leviathan',
    weapon: '🐋',
    baseCost: 210,
    power: 13,
    godmode: 9,
    effectClass: 'frost',
    animated: true,
    animationName: 'Archive-Horizon Leviathan',
    description: 'NEW · Mythic — cold-storage kaiju; vault opens and the golden Orion key emerges from frost.',
  },
  {
    id: 'brain-secret-sphinx',
    name: 'Brain-Secret Sphinx',
    weapon: '🦁',
    baseCost: 64,
    power: 6,
    godmode: 3,
    effectClass: 'godmode-key',
    animated: true,
    animationName: 'Brain-Secret Sphinx',
    description: 'NEW · Epic — riddle of the mind; mental constellation seals without writing the secret.',
  },
  {
    id: 'orbit-ring-dancer',
    name: 'Orbit Ring Dancer',
    weapon: '💫',
    baseCost: 36,
    power: 4,
    godmode: 2,
    effectClass: 'neon',
    animated: true,
    animationName: 'Orbit Ring Dancer',
    description: 'NEW · Rare — ballet of cipher rings; reverse spin locks into a nested gold seal pose.',
  },
  {
    id: 'strongbox-beetle',
    name: 'StrongBox Beetle',
    weapon: '🪲',
    baseCost: 15,
    power: 2,
    godmode: 1,
    effectClass: 'spark-net',
    animated: true,
    animationName: 'StrongBox Beetle',
    description: 'NEW · Common — hardware-rooted scarab; shell iris opens then snaps sealed with gold flash.',
  },
  {
    id: 'null-cipher-phantom',
    name: 'Null-Cipher Phantom',
    weapon: '🫥',
    baseCost: 125,
    power: 10,
    godmode: 6,
    effectClass: 'glitch',
    animated: true,
    animationName: 'Null-Cipher Phantom',
    description: 'NEW · Legendary — opaque ciphertext silhouette; final gold seal stamp, then vanish.',
  },
  {
    id: 'constellation-keysmith',
    name: 'Constellation Keysmith',
    weapon: '⚒️',
    baseCost: 74,
    power: 7,
    godmode: 4,
    effectClass: 'pulse-cannon',
    animated: true,
    animationName: 'Constellation Keysmith',
    description: 'NEW · Epic — forges keys from stars; three strikes (Secret / Sky / Seal) quench the Orion key.',
  },
  {
    id: 'assurance-throne-mythic',
    name: 'Assurance Throne Mythic',
    weapon: '⚜️',
    baseCost: 220,
    power: 14,
    godmode: 10,
    effectClass: 'solar',
    animated: true,
    animationName: 'Assurance Throne Mythic',
    description: 'NEW · Mythic — endgame throne; dual keys, Argon pedestals, sky pins, royal ASSURED seal.',
  },
]

/* ── Premium WebM gifts — batch 3 ───────────────────────────────────────── */
const PREMIUM_VIDEO_GIFTS_B3b: BattleGift[] = [
  {
    id: 'golden-lion-king',
    name: 'Golden Lion King',
    weapon: '🦁',
    baseCost: 130,
    power: 10,
    godmode: 6,
    effectClass: 'solar',
    animated: true,
    animationName: 'Golden Lion King',
    videoSrc: '/gifts/01_Golden_Lion_King.webm',
    description: '🦁 The Lion King rules — absolute top-tier score nuke.',
  },
  {
    id: 'diamond-orbit',
    name: 'Diamond Orbit',
    weapon: '💎',
    baseCost: 84,
    power: 8,
    godmode: 4,
    effectClass: 'frost',
    animated: true,
    animationName: 'Diamond Orbit',
    videoSrc: '/gifts/02_Diamond_Orbit.webm',
    description: 'Diamonds orbit the target — precision crystal barrage.',
  },
  {
    id: 'money-tornado',
    name: 'Money Tornado',
    weapon: '🌪️',
    baseCost: 64,
    power: 7,
    godmode: 3,
    effectClass: 'vortex',
    animated: true,
    animationName: 'Money Tornado',
    videoSrc: '/gifts/03_Money_Tornado.webm',
    description: 'Cash vortex tears through — big score pressure.',
  },
  {
    id: 'fire-phoenix',
    name: 'Fire Phoenix',
    weapon: '🦅',
    baseCost: 74,
    power: 7,
    godmode: 4,
    effectClass: 'solar',
    animated: true,
    animationName: 'Fire Phoenix',
    videoSrc: '/gifts/04_Fire_Phoenix.webm',
    description: 'Phoenix ignites — fire sweep charges Godmode and score.',
  },
  {
    id: 'neon-ufo',
    name: 'Neon UFO',
    weapon: '🛸',
    baseCost: 54,
    power: 5,
    godmode: 3,
    effectClass: 'neon',
    animated: true,
    animationName: 'Neon UFO',
    videoSrc: '/gifts/05_Neon_UFO.webm',
    description: 'UFO abducts the score — neon tractor beam hit.',
  },
  {
    id: 'royal-crown',
    name: 'Royal Crown',
    weapon: '👑',
    baseCost: 94,
    power: 9,
    godmode: 5,
    effectClass: 'solar',
    animated: true,
    animationName: 'Royal Crown',
    videoSrc: '/gifts/06_Royal_Crown.webm',
    description: '👑 Crown descends — royal domination hit.',
  },
  {
    id: 'love-burst',
    name: 'Love Burst',
    weapon: '💖',
    baseCost: 44,
    power: 5,
    godmode: 2,
    effectClass: 'spark-net',
    animated: true,
    animationName: 'Love Burst',
    videoSrc: '/gifts/07_Love_Burst.webm',
    description: 'Heart bursts — crowd favourite score booster.',
  },
  {
    id: 'crystal-sword-v2',
    name: 'Crystal Sword II',
    weapon: '🗡️',
    baseCost: 69,
    power: 7,
    godmode: 3,
    effectClass: 'frost',
    animated: true,
    animationName: 'Crystal Sword II',
    videoSrc: '/gifts/08_Crystal_Sword.webm',
    description: 'Second blade drops — ice slash combo hit.',
  },
  {
    id: 'space-whale',
    name: 'Space Whale',
    weapon: '🐋',
    baseCost: 59,
    power: 6,
    godmode: 3,
    effectClass: 'vortex',
    animated: true,
    animationName: 'Space Whale',
    videoSrc: '/gifts/09_Space_Whale.webm',
    description: 'Cosmic whale breaches — gravity wave score hit.',
  },
  {
    id: 'lightning-dragon',
    name: 'Lightning Dragon',
    weapon: '🐲',
    baseCost: 109,
    power: 10,
    godmode: 5,
    effectClass: 'thunder',
    animated: true,
    animationName: 'Lightning Dragon',
    videoSrc: '/gifts/10_Lightning_Dragon.webm',
    description: '🐲 Lightning dragon strikes — electric chain hit, max power.',
  },
]

/* ── Premium WebM gifts — batch 2 ───────────────────────────────────────── */
const PREMIUM_VIDEO_GIFTS_B2: BattleGift[] = [
  {
    id: 'meteor-shower',
    name: 'Meteor Shower',
    weapon: '☄️',
    baseCost: 54,
    power: 6,
    godmode: 3,
    effectClass: 'meteor',
    animated: true,
    animationName: 'Meteor Shower',
    videoSrc: '/gifts/01_Meteor_Shower.webm',
    description: 'Relentless meteor rain — heavy score pressure on the target.',
  },
  {
    id: 'cyber-cat',
    name: 'Cyber Cat',
    weapon: '🐱',
    baseCost: 34,
    power: 3,
    godmode: 2,
    effectClass: 'neon',
    animated: true,
    animationName: 'Cyber Cat',
    videoSrc: '/gifts/02_Cyber_Cat.webm',
    description: 'Neon cyber kitty attack — quick and chaotic.',
  },
  {
    id: 'angel-wings',
    name: 'Angel Wings',
    weapon: '🪽',
    baseCost: 64,
    power: 5,
    godmode: 4,
    effectClass: 'solar',
    animated: true,
    animationName: 'Angel Wings',
    videoSrc: '/gifts/03_Angel_Wings.webm',
    description: 'Divine wing burst — high Godmode charge and score lift.',
  },
  {
    id: 'neon-skull',
    name: 'Neon Skull',
    weapon: '💀',
    baseCost: 74,
    power: 7,
    godmode: 3,
    effectClass: 'glitch',
    animated: true,
    animationName: 'Neon Skull',
    videoSrc: '/gifts/04_Neon_Skull.webm',
    description: 'Glitch skull strike — corrupts the screen and hammers the score.',
  },
  {
    id: 'magic-portal',
    name: 'Magic Portal',
    weapon: '🌀',
    baseCost: 84,
    power: 8,
    godmode: 4,
    effectClass: 'vortex',
    animated: true,
    animationName: 'Magic Portal',
    videoSrc: '/gifts/05_Magic_Portal.webm',
    description: 'Portal opens — massive vortex hit, top-tier score damage.',
  },
  {
    id: 'ice-dragon',
    name: 'Ice Dragon',
    weapon: '🐉',
    baseCost: 94,
    power: 9,
    godmode: 5,
    effectClass: 'frost',
    animated: true,
    animationName: 'Ice Dragon',
    videoSrc: '/gifts/06_Ice_Dragon.webm',
    description: '🐉 Ice dragon breath — freezing assault, max Godmode unlock.',
  },
  {
    id: 'love-explosion',
    name: 'Love Explosion',
    weapon: '💥',
    baseCost: 44,
    power: 5,
    godmode: 2,
    effectClass: 'spark-net',
    animated: true,
    animationName: 'Love Explosion',
    videoSrc: '/gifts/07_Love_Explosion.webm',
    description: 'Heart detonation — crowd-pleasing blast for solid score gain.',
  },
  {
    id: 'treasure-chest',
    name: 'Treasure Chest',
    weapon: '🪙',
    baseCost: 49,
    power: 4,
    godmode: 3,
    effectClass: 'spark-net',
    animated: true,
    animationName: 'Treasure Chest',
    videoSrc: '/gifts/08_Treasure_Chest.webm',
    description: 'Chest bursts open — coins fly and Godmode charges.',
  },
  {
    id: 'electric-storm',
    name: 'Electric Storm',
    weapon: '⚡',
    baseCost: 79,
    power: 8,
    godmode: 4,
    effectClass: 'thunder',
    animated: true,
    animationName: 'Electric Storm',
    videoSrc: '/gifts/09_Electric_Storm.webm',
    description: 'Lightning storm blitz — chain strikes for massive score damage.',
  },
  {
    id: 'supernova',
    name: 'Supernova',
    weapon: '🌟',
    baseCost: 120,
    power: 10,
    godmode: 6,
    effectClass: 'solar',
    animated: true,
    animationName: 'Supernova',
    videoSrc: '/gifts/10_Supernova.webm',
    description: '🌟 SUPERNOVA — the ultimate gift. Instant score nuke + full Godmode.',
  },
]

/* ── Premium WebM gifts — batch 1 ───────────────────────────────────────── */
const PREMIUM_VIDEO_GIFTS: BattleGift[] = [
  {
    id: 'golden-crown',
    name: 'Golden Crown',
    weapon: '👑',
    baseCost: 99,
    power: 8,
    godmode: 4,
    effectClass: 'solar',
    animated: true,
    animationName: 'Golden Crown',
    videoSrc: '/gifts/01_Golden_Crown.webm',
    description: '👑 Supreme hit — massive score + Godmode boost.',
  },
  {
    id: 'galaxy-heart',
    name: 'Galaxy Heart',
    weapon: '💜',
    baseCost: 49,
    power: 5,
    godmode: 3,
    effectClass: 'vortex',
    animated: true,
    animationName: 'Galaxy Heart',
    videoSrc: '/gifts/02_Galaxy_Heart.webm',
    description: 'Galaxy love attack — pulls the crowd and pressures the target.',
  },
  {
    id: 'diamond-drop',
    name: 'Diamond Drop',
    weapon: '💎',
    baseCost: 79,
    power: 7,
    godmode: 3,
    effectClass: 'frost',
    animated: true,
    animationName: 'Diamond Drop',
    videoSrc: '/gifts/03_Diamond_Drop.webm',
    description: 'Diamond hail — crystalline barrage for a big score push.',
  },
  {
    id: 'rocket-blast',
    name: 'Rocket Blast',
    weapon: '🚀',
    baseCost: 39,
    power: 4,
    godmode: 2,
    effectClass: 'meteor',
    animated: true,
    animationName: 'Rocket Blast',
    videoSrc: '/gifts/04_Rocket_Blast.webm',
    description: 'Full-speed rocket hit — fast score damage.',
  },
  {
    id: 'phoenix-flame',
    name: 'Phoenix Flame',
    weapon: '🔥',
    baseCost: 69,
    power: 6,
    godmode: 4,
    effectClass: 'solar',
    animated: true,
    animationName: 'Phoenix Flame',
    videoSrc: '/gifts/05_Phoenix_Flame.webm',
    description: 'Phoenix rises — fire sweep hits score and unlocks Godmode.',
  },
  {
    id: 'butterfly-neon',
    name: 'Butterfly Neon',
    weapon: '🦋',
    baseCost: 29,
    power: 3,
    godmode: 2,
    effectClass: 'neon',
    animated: true,
    animationName: 'Butterfly Neon',
    videoSrc: '/gifts/06_Butterfly_Neon.webm',
    description: 'Neon butterfly strike — light, fast, and stylish.',
  },
  {
    id: 'dragon-egg',
    name: 'Dragon Egg',
    weapon: '🥚',
    baseCost: 89,
    power: 9,
    godmode: 5,
    effectClass: 'neon',
    animated: true,
    animationName: 'Dragon Egg',
    videoSrc: '/gifts/07_Dragon_Egg.webm',
    description: '🐉 The rarest hit — dragon hatches for maximum score damage.',
  },
  {
    id: 'money-rain',
    name: 'Money Rain',
    weapon: '💸',
    baseCost: 59,
    power: 5,
    godmode: 2,
    effectClass: 'spark-net',
    animated: true,
    animationName: 'Money Rain',
    videoSrc: '/gifts/08_Money_Rain.webm',
    description: 'Cash downpour — floods the screen and boosts team score.',
  },
  {
    id: 'crystal-sword',
    name: 'Crystal Sword',
    weapon: '⚔️',
    baseCost: 59,
    power: 6,
    godmode: 3,
    effectClass: 'frost',
    animated: true,
    animationName: 'Crystal Sword',
    videoSrc: '/gifts/09_Crystal_Sword.webm',
    description: 'Ice blade slash — precision strike for score and Godmode.',
  },
  {
    id: 'magic-orb',
    name: 'Magic Orb',
    weapon: '🔮',
    baseCost: 44,
    power: 4,
    godmode: 3,
    effectClass: 'vortex',
    animated: true,
    animationName: 'Magic Orb',
    videoSrc: '/gifts/10_Magic_Orb.webm',
    description: 'Mystic orb explosion — unpredictable energy burst.',
  },
]

const ANIMATION_NAMES = [
  'Spark Net', 'Pulse Cannon', 'Shield Break', 'Godmode Key', 'Meteor Drop', 'Neon Dragon', 'Ice Lance',
  'Solar Flare', 'Thunder Drum', 'Gravity Slam', 'Plasma Wave', 'Crystal Barrage', 'Comet Chain',
  'Vortex Kick', 'Laser Halo', 'Frost Nova', 'Phoenix Sweep', 'Quantum Hammer', 'Starfall Beam',
  'Blizzard Wall', 'Arc Blade', 'Rocket Bloom', 'Tidal Crush', 'Nova Spear', 'Prism Storm',
  'Titan Clap', 'Shadow Ribbon', 'Fireworks Rush', 'Magnet Trap', 'Lightning Crown', 'Orbit Strike',
  'Cyber Cyclone', 'Moonshot', 'Glitch Grenade', 'Avalanche Bell', 'Dragonfly Swarm', 'Sun Disk',
  'Echo Mine', 'Diamond Rain', 'Turbo Tornado', 'Ion Harpoon', 'Sonic Burst', 'Aurora Trap',
  'Nebula Bite', 'Laser Carousel', 'Pulse Wolf', 'Crystal Kraken', 'Final Rift', 'Matrix Bloom',
]

const STATIC_GIFT_NAMES = [
  'Team Banner', 'Hype Horn', 'Combo Token', 'Energy Patch', 'Shield Chip', 'Boost Badge', 'Rally Flag',
  'Focus Lens', 'Heat Meter', 'Power Seed', 'Bonus Bell', 'Strike Coin', 'Crowd Roar', 'XP Ribbon',
  'Momentum Pin', 'Crew Signal', 'Target Mark', 'Guard Plate', 'Level Tile', 'Score Spark', 'Bounty Note',
  'Victory Stamp', 'Chat Crown', 'Arena Pass', 'Duel Drum', 'Assist Tag', 'Clutch Card', 'Power Vote',
  'Battle Charm', 'Rank Flame', 'Stage Light', 'Focus Ring', 'Team Echo', 'Win Thread', 'Signal Boost',
  'Match Key', 'Cheer Stack', 'Bonus Brick', 'Arcade Chip', 'Room Torch', 'Wave Token', 'Orbit Coin',
  'Creator Clap', 'MVP Marker', 'Lucky Switch', 'Final Push', 'Edge Badge', 'Godmode Seed', 'Break Point',
  'Legend Toast',
]

const EFFECT_CLASSES = [
  'spark-net',
  'pulse-cannon',
  'shield-break',
  'godmode-key',
  'meteor',
  'neon',
  'frost',
  'solar',
  'thunder',
  'vortex',
  'glitch',
]

function slugify(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
}

function makeWeaponLabel(name: string): string {
  return name
    .split(' ')
    .map((part) => part[0])
    .join('')
    .slice(0, 5)
    .toUpperCase()
}

const GENERATED_ANIMATED_GIFTS: BattleGift[] = ANIMATION_NAMES.map((name, index) => ({
  id: slugify(name),
  name,
  weapon: makeWeaponLabel(name),
  baseCost: 10 + index * 3,
  power: 2 + (index % 9),
  godmode: 1 + (index % 4),
  effectClass: EFFECT_CLASSES[index % EFFECT_CLASSES.length],
  animated: true,
  animationName: `${name} animation`,
  description: 'Premium animated battle hit for team pressure and live-room spectacle.',
}))

const STATIC_GIFTS: BattleGift[] = STATIC_GIFT_NAMES.map((name, index) => ({
  id: slugify(name),
  name,
  weapon: makeWeaponLabel(name),
  baseCost: 6 + index * 2,
  power: 1 + (index % 6),
  godmode: index % 5 === 0 ? 2 : 1,
  effectClass: 'static-boost',
  animated: false,
  description: 'Battle boost gift for score pressure without a premium animation.',
}))

export const BATTLE_GIFTS: BattleGift[] = [
  ...ORION_KEY_AVATAR_GIFTS,   /* NEW — Tick Tock Prime × Orion Key (20 avatar concepts) */
  ...LEGENDARY_GIFTS,          /* Golden Rose */
  ...PREMIUM_VIDEO_GIFTS_B3b,  /* batch 3 — 10 WebM gifts */
  ...PREMIUM_VIDEO_GIFTS_B2,   /* batch 2 — 10 WebM gifts */
  ...PREMIUM_VIDEO_GIFTS,      /* batch 1 — 10 WebM gifts */
  ...ANIMATED_GIFTS,
  ...GENERATED_ANIMATED_GIFTS,
  ...STATIC_GIFTS,
].slice(0, 140)

export const ANIMATED_BATTLE_GIFT_COUNT = BATTLE_GIFTS.filter((gift) => gift.animated).length

export function discountedCost(baseCost: number): number {
  return Math.max(1, Math.ceil(baseCost * (1 - BATTLE_DISCOUNT)))
}

export function splitBattleRevenue(gross: number): BattleRevenueSplit {
  const creator = Math.floor(gross * CREATOR_REVENUE_RATE)
  return {
    gross,
    creator,
    networkDesigners: gross - creator,
  }
}
